### ISSUE TITLE
Property Collection Table Naming Convention

### ISSUE THREAD

**Issue by acgentry** [Particular/NServiceBus.NHibernate#94] opened 2015-04-23 13:21 UTC
This is an improvement request to how collection tables get named for Saga persistence, I believe this would fall into this project but not sure.

Currently tables get generated in a way that could cause collisions in property names.  For example a class Foo with a collection property of Bar will create two tables: Bar & Foo

My recommendation is to create two tables of: Bar & Bar.Foo OR Bar_Foo

Ideally it would be great to have this saga persistence in its own sql schema per application/namespace, but I would settle for the table improvement. :)

Thanks!

**Comment by johnsimons** [comment] 2015-04-24 00:30
Hi @acgentry 
The default for table creation should be "Bar_Foo", how do I reproduce this issue?

Also you can control the conventions, you can either annotate your classes with `TableNameAttribute` or:
```c#
config.UsePersistence<NHibernatePersistence>().SagaTableNamingConvention(t =>
                {
                    // return the name you want for the type
                });
```

Here are the default conventions, see https://github.com/Particular/NServiceBus.NHibernate/blob/57c1b3bab13022f396da6984c6fa9825ff71eb4f/src/NServiceBus.NHibernate/SagaPersisters/SagaModelMapper.cs#L114-L128

Does this work for you ?

**Comment by acgentry** [comment] 2015-04-24 12:46
Thanks for the pointer to the naming convention feature, now it seems like a defect, for the class the saga class is marked with ContainsSagaData and has a property of:

public virtual IList<RequestLog> Logs { get; set; }

The RequestLog is a POCO that when persisted creates a Logs table without the prefix of the owner sagadata class.

**Comment by johnsimons** [comment] 2015-04-27 23:59
@acgentry yes, at the moment is not possible to supply naming conventions for classes that do not have an id.
If you add `public virtual Guid Id { get; set; }` to `RequestLog`, it should start working, because then the convention applies.

**Comment by johnsimons** [comment] 2015-04-28 00:06
@andreasohlund @SzymonPobiega, so this issue is the following.
Given a saga data looking like this:
```c#
public class TestSagaData : ContainSagaData
{
    [Unique]
    public virtual Guid SomeId { get; set; }
    public virtual IList<ChildData> RelatedData { get; set; }
    public virtual IList<RequestLog> Logs { get; set; }
}

public class ChildData
{
    public virtual Guid Id { get; set; }
    public virtual string Data { get; set; }
}

public class RequestLog
{
    public virtual string Data { get; set; }
}
```

We get 3 tables created:
- [Saga_Class_Name]
- [Saga_Class_Name]_ChildData
- Logs 

So it looks like for `public virtual IList<RequestLog> Logs { get; set; }` the table naming conventions are not applied.
The fix is simple, we just need to modify:
```c#
void ApplyBagConvention(IModelInspector mi, PropertyPath type, IBagPropertiesMapper map)
{
    map.Cascade(Cascade.All | Cascade.DeleteOrphans);
    map.Key(km => km.Column(type.LocalMember.DeclaringType.Name + "_id"));

    var bagType = type.LocalMember.GetPropertyOrFieldType().DetermineCollectionElementType();
    var parentType = type.LocalMember.DeclaringType;

    // New code to use conventions
    var namingConvention = tableNamingConvention(bagType);
    map.Table(namingConvention);

    if (bagType.HasPublicPropertyOf(parentType))
    {
        map.Inverse(true);
    }
}
```

But obviously this is a non backwards compatible change, so how do we handle it ?

**Comment by SzymonPobiega** [comment] 2015-04-28 06:27
@johnsimons I think this is a part of greater discussion about future of NH saga mapping. IMO a decent option is to serialize to JSON by default but allow users who need normalized tables to explicitly provide mappings.

**Comment by johnsimons** [comment] 2015-04-28 21:53
> I think this is a part of greater discussion about future of NH saga mapping. IMO a decent option is to serialize to JSON by default but allow users who need normalized tables to explicitly provide mappings.

@SzymonPobiega even though what you saying is interesting, I don't think it is relevant for this discussion, I suggest you raising a requirement about it.

How about the question I asked ?

**Comment by SzymonPobiega** [comment] 2015-04-29 06:26
@johnsimons what I meant is that doing such a breaking change should be considered via requirements and that we *might* (don't say we will) end up removing the mappings entirely.

**Comment by indualagarsamy** [comment] 2016-07-05 19:19
@SzymonPobiega @johnsimons - any updates on this?

**Comment by johnsimons** [comment] 2016-07-05 21:16
@indualagarsamy as explained in https://github.com/Particular/NServiceBus.NHibernate/issues/94#issuecomment-96853780, this change will fix the issue.

For us to do this magically we would need changes as explained in https://github.com/Particular/NServiceBus.NHibernate/issues/94#issuecomment-96854564 and that won't be backwards compatible, so I am inclined to close this as won't fix.

@Particular/nhibernate-persistence-maintainers thoughts ?

**Comment by SzymonPobiega** [comment] 2017-07-05 12:21
We don't plan to release a major in near future so I am closing this one. Let's re open if the problem pops up again.

**Closed by SzymonPobiega** 2017-07-05 12:21 UTC
Labels: Bug
