### ISSUE TITLE
[Regression] NServiceBus generates wrong script for creating the outbox table for PosgreSQL

### ISSUE THREAD

**Issue by dvorak-jan** [Particular/NServiceBus.NHibernate#106] opened 2015-06-16 08:40 UTC
Issue [#74](https://github.com/Particular/NServiceBus.NHibernate/issues/74) is back in the latest version 6.2.0.

The issue has been fixed in version 6.0.2 by this commit https://github.com/Particular/NServiceBus.NHibernate/commit/d7c16a20a3bf6796dd7b9105c9d2996c605b0da5.

---

### Symptoms
when initializing PostgreSQL storage (9.4) using NServiceBus.NHibernate 6.2.0 the exception is thrown and no tables are created (outbox, timeouts).

```
Schema update failed.
The following exception(s) were thrown:
System.AggregateException: One or more errors occurred. ---> Npgsql.NpgsqlException: ERROR: 42804: column "dispatched" is of type boolean but default expression is of type integer
   at Npgsql.NpgsqlState.<ProcessBackendResponses>d__0.MoveNext()
   at Npgsql.ForwardsOnlyDataReader.GetNextResponseObject(Boolean cleanup)
   at Npgsql.ForwardsOnlyDataReader.GetNextRowDescription()
   at Npgsql.ForwardsOnlyDataReader.NextResultInternal()
   at Npgsql.ForwardsOnlyDataReader..ctor(IEnumerable`1 dataEnumeration, CommandBehavior behavior, NpgsqlCommand command, NotificationThreadBlock threadBlock, Boolean preparedStatement, NpgsqlRowDescription rowDescription)
   at Npgsql.NpgsqlCommand.GetReader(CommandBehavior cb)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at NHibernate.Tool.hbm2ddl.SchemaUpdate.Execute(Action`1 scriptAction, Boolean doUpdate)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Npgsql.NpgsqlException:
column "dispatched" is of type boolean but default expression is of type integer
Severity: ERROR
Code: 42804
Hint: You will need to rewrite or cast the expression.
   at Npgsql.NpgsqlState.<ProcessBackendResponses>d__0.MoveNext()
   at Npgsql.ForwardsOnlyDataReader.GetNextResponseObject(Boolean cleanup)
   at Npgsql.ForwardsOnlyDataReader.GetNextRowDescription()
   at Npgsql.ForwardsOnlyDataReader.NextResultInternal()
   at Npgsql.ForwardsOnlyDataReader..ctor(IEnumerable`1 dataEnumeration, CommandBehavior behavior, NpgsqlCommand command, NotificationThreadBlock threadBlock, Boolean preparedStatement, NpgsqlRowDescription rowDescription)
   at Npgsql.NpgsqlCommand.GetReader(CommandBehavior cb)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at NHibernate.Tool.hbm2ddl.SchemaUpdate.Execute(Action`1 scriptAction, Boolean doUpdate)<---

---> (Inner Exception #1) Npgsql.NpgsqlException:
relation "outboxrecord" does not exist
Severity: ERROR
Code: 42P01
   at Npgsql.NpgsqlState.<ProcessBackendResponses>d__0.MoveNext()
   at Npgsql.ForwardsOnlyDataReader.GetNextResponseObject(Boolean cleanup)
   at Npgsql.ForwardsOnlyDataReader.GetNextRowDescription()
   at Npgsql.ForwardsOnlyDataReader.NextResultInternal()
   at Npgsql.ForwardsOnlyDataReader..ctor(IEnumerable`1 dataEnumeration, CommandBehavior behavior, NpgsqlCommand command, NotificationThreadBlock threadBlock, Boolean preparedStatement, NpgsqlRowDescription rowDescription)
   at Npgsql.NpgsqlCommand.GetReader(CommandBehavior cb)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at NHibernate.Tool.hbm2ddl.SchemaUpdate.Execute(Action`1 scriptAction, Boolean doUpdate)<---

---> (Inner Exception #2) Npgsql.NpgsqlException:
relation "outboxrecord" does not exist
Severity: ERROR
Code: 42P01
   at Npgsql.NpgsqlState.<ProcessBackendResponses>d__0.MoveNext()
   at Npgsql.ForwardsOnlyDataReader.GetNextResponseObject(Boolean cleanup)
   at Npgsql.ForwardsOnlyDataReader.GetNextRowDescription()
   at Npgsql.ForwardsOnlyDataReader.NextResultInternal()
   at Npgsql.ForwardsOnlyDataReader..ctor(IEnumerable`1 dataEnumeration, CommandBehavior behavior, NpgsqlCommand command, NotificationThreadBlock threadBlock, Boolean preparedStatement, NpgsqlRowDescription rowDescription)
   at Npgsql.NpgsqlCommand.GetReader(CommandBehavior cb)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at NHibernate.Tool.hbm2ddl.SchemaUpdate.Execute(Action`1 scriptAction, Boolean doUpdate)<---


TSql Script:

    create table OutboxRecord (
        Id  bigserial,
       MessageId varchar(255) not null unique,
       Dispatched boolean default 0  not null,
       DispatchedAt timestamp,
       TransportOperations text,
       primary key (Id)
    )

    create index OutboxRecord_Dispatched_Idx on OutboxRecord (Dispatched)

    create index OutboxRecord_DispatchedAt_Idx on OutboxRecord (DispatchedAt)
```

### Who's affected

PostreSQL users

**Comment by andreasohlund** [comment] 2015-06-23 17:04
@dvorak-jan thanks for the report, we're investigating this and also figuring out why this regression happened. 

We'll keep you posted

**Comment by SzymonPobiega** [comment] 2015-07-16 12:38
@dvorak-jan it seems like the reason for the regression is the fact that the changes from the 6.0.2 hotfix branch have not been merged to develop. Working on that.

**Closed** 2015-07-20 14:50 UTC
Labels: Bug
