### ISSUE TITLE
Installers won't bootstrap persistence and transport

### ISSUE THREAD

**Issue by janpieterz** [Particular/NServiceBus.NHibernate#197] opened 2016-06-03 16:19 UTC
The installer, using the host `
NServiceBus
.Host.exe -install -serviceName ENMServer -displayName ENMServer -description "ENMServer" /install NServiceBus.Production` didn't create the required transport and persistence. My Octopus Deployment scripts of other projects call this and it always seems to have been created fine (running older NSB (5.14 and either RabbitMQ or Azure Service Bus)). This one runs beta0003 of NHibernate and beta0002 of hosting.

For now I just fixed it by running from VS with the remote database, but it's still good to know what else to do, or that there is a bug.

**Comment by DavidBoike** [comment] 2016-06-06 18:36
Hi @janpieterz, thanks for the report!

This is definitely a bug, caused by a change in how NServiceBus starts up in V6. We will get it fixed before Release Candidate, and the fix will likely be available in a forthcoming beta before that.

It's actually a bug in the NServiceBus Core, so I'm closing this issue and I opened https://github.com/Particular/NServiceBus/issues/3807 to replace it.

**Closed by DavidBoike** 2016-06-06 18:36 UTC

**Comment by DavidBoike** [comment] 2016-06-21 14:54
@janpieterz Just wanted to let you know that the bug is now fixed in our 6.0 release branch. When the NServiceBus Core Beta 5 goes out, it will include the fix.

**Comment by janpieterz** [comment] 2016-06-21 20:34
@DavidBoike Superb, thanks, also saw the other thread. Thanks for the swift response guys, the insight gained from the process like this is much appreciated!
